version: "3"

tasks:
  build:
    desc: Build the application
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/go-rest-api internal/main.go
  
  run:
    desc: Run the application
    cmds:
      - GOFLAGS=-mod=mod go run internal/main.go

  swagger.gen:
    desc: Generate Go code
    cmds:
      - GOFLAGS=-mod=mod go generate github.com/glaucoleme/learn-go-by-examples/go-rest-api/internal github.com/glaucoleme/learn-go-by-examples/go-rest-api/pkg/swagger

  swagger.validate:
    desc: Validate the swagger file
    cmds:
      - swagger validate pkg/swagger/swagger.yml
  
  swagger.doc:
    desc: Documentation for swagger
    cmds:
      - docker run --rm -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html

  swagger.view:
    desc: Show swagger documentation as HTTP page
    cmds:
      - python3 -m http.server --directory doc/